FROM amazon/aws-cli:2.2.41

# install terraform
RUN yum update && yum install -y yum-utils
RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
RUN yum -y install terraform
